
---
apiVersion: v1
kind: Namespace
metadata:
  name: teste-build
  labels:
    app : teste
    team: Diego Rodrigues
    build-namespace: teste-build
    size: small
    environment: build
    goldilocks.fairwinds.com/enabled: "true"
    argocd.argoproj.io/managed-by: teste-build

---
apiVersion: v1
kind: Namespace
metadata:
  name: teste-dev
  labels:
    app : teste
    team: Diego Rodrigues
    build-namespace: teste-build
    size: small
    environment: dev
    goldilocks.fairwinds.com/enabled: "true"
    argocd.argoproj.io/managed-by: teste-build

---
apiVersion: v1
kind: Namespace
metadata:
  name: teste-qa
  labels:
    app : teste
    team: Diego Rodrigues
    build-namespace: teste-build
    size: small
    environment: qa
    goldilocks.fairwinds.com/enabled: "true"
    argocd.argoproj.io/managed-by: teste-build

---
apiVersion: v1
kind: Namespace
metadata:
  name: teste-prod
  labels:
    app : teste
    team: Diego Rodrigues
    build-namespace: teste-build
    size: small
    environment: prod
    goldilocks.fairwinds.com/enabled: "true"
    argocd.argoproj.io/managed-by: teste-build
